//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Browser")]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CreditField;
        
        private int FanNumField;
        
        private int FollowNumField;
        
        private string IntroField;
        
        private bool IsVerifiedField;
        
        private int LevelField;
        
        private string LocationField;
        
        private string NickNameField;
        
        private bool SexField;
        
        private string UidField;
        
        private int WeiboNumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanNum
        {
            get
            {
                return this.FanNumField;
            }
            set
            {
                this.FanNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FollowNum
        {
            get
            {
                return this.FollowNumField;
            }
            set
            {
                this.FollowNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intro
        {
            get
            {
                return this.IntroField;
            }
            set
            {
                this.IntroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                this.NickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid
        {
            get
            {
                return this.UidField;
            }
            set
            {
                this.UidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeiboNum
        {
            get
            {
                return this.WeiboNumField;
            }
            set
            {
                this.WeiboNumField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserInfoService")]
public interface IUserInfoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserInfoService/GetUserInfo", ReplyAction="http://tempuri.org/IUserInfoService/GetUserInfoResponse")]
    Browser.UserInfo GetUserInfo(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserInfoService/GetUserInfo", ReplyAction="http://tempuri.org/IUserInfoService/GetUserInfoResponse")]
    System.Threading.Tasks.Task<Browser.UserInfo> GetUserInfoAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserInfoServiceChannel : IUserInfoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserInfoServiceClient : System.ServiceModel.ClientBase<IUserInfoService>, IUserInfoService
{
    
    public UserInfoServiceClient()
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Browser.UserInfo GetUserInfo(string name)
    {
        return base.Channel.GetUserInfo(name);
    }
    
    public System.Threading.Tasks.Task<Browser.UserInfo> GetUserInfoAsync(string name)
    {
        return base.Channel.GetUserInfoAsync(name);
    }
}
